name: Deploy lkpc-frontend to S3

# Triggers on push to main and dev branches
on:
  push:
    branches:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Build the app
      - name: Build the app
        run: |
          npm run build

      # Setup AWS CLI with the environment variables
      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Check AWS Credentials
        run: |
          aws sts get-caller-identity --debug

      # Deploy to AWS (dev or prod)
      - name: Deploy to AWS
        run: aws s3 sync out/ s3://lkpc-hosting-dev --delete
